* Dust trajectories in bow shocks
This is an extension of the models I have done in ~dust-wave.org~ from the Jorge bow shock project. 
+ 1d and 3d models for the trajectories of charged dust grains under 3 forces
  1. Radiation from a star
  2. Gas-grain drag
     - Stokes drag (solid body), important at supersonic relative speeds
     - Coulomb drag, peaks at roughly 10 km/s for ionized gas
  3. Lorentz force, couples grains to B-field
+ Main scenario considered is a stream of dusty plasma, incident on a star


* Drag force
+ Functional form from Draine & Salpeter
+ Calibrated from Cloudy models
  + Major contribution is from protons
  + But does include the minor contribution from electrons and helium ions
  + Electrons fill in the minimum around 100 km/s
  + Helium adds a shoulder to the peak around 5 km/s
+ Implemented in [[file:ds79.py]]
+ Note that it is normalized by the gas pressure and the grain cross-sectional area
** Test drag force
#+BEGIN_SRC python :results file :return pltfile
  import numpy as np
  import ds79
  from matplotlib import pyplot as plt
  import seaborn as sns

  pltfile = "test-Fdrag-exact.pdf"

  w = np.logspace(-1.5, 3.5, 200)

  fig, ax = plt.subplots()

  for phi in 0.25, 1.0, 4.0, 16.0:
      ax.plot(w, ds79.Fdrag(w, T=8000, phi=phi, n=100), label=rf"$\phi = {phi:.2f}$")
  ax.legend(title="Grain potential")
  ax.set(
      xscale="log",
      yscale="log",
      xlabel="Gas-grain velocity difference, $w$, km/s",
      ylabel=r"Drag force $/ (2 n k T) (\pi a^{2}) $",
  )
  sns.despine()
  fig.tight_layout()
  fig.savefig(pltfile)
#+END_SRC

#+RESULTS:
[[file:test-Fdrag-exact.pdf]]
** Components of drag force
+ Metal abundances for gas-phase ISM from Cloudy.  Here I list all elements with abundances higher than 1 part-per-million
  |    |         |         abun |  A |       abun*A |
  |----+---------+--------------+----+--------------|
  | C  | -3.5229 | 2.9998532e-4 | 12 | 3.5998238e-3 |
  | N  | -4.1549 | 7.0000316e-5 | 14 | 9.8000442e-4 |
  | O  | -3.3979 | 4.0003685e-4 | 16 | 6.4005896e-3 |
  | Ne | -4.2218 | 6.0006735e-5 | 20 | 1.2001347e-3 |
  | Mg | -5.5229 | 2.9998532e-6 | 24 | 7.1996477e-5 |
  | Si | -5.3979 | 4.0003685e-6 | 28 | 1.1201032e-4 |
  | S  | -5.0000 |         1e-5 | 32 |       3.2e-4 |
  | Ar | -5.5229 | 2.9998532e-6 | 40 | 1.1999413e-4 |
  | Fe | -5.5229 | 2.9998532e-6 | 56 | 1.6799178e-4 |
  |----+---------+--------------+----+--------------|
  |    |         |      0.00085 |    |         15.3 |
  #+TBLFM: $3=10**$-1::$5=$-1 $-2::@11$3=vsum(@I..@II);f5::@11$5=vsum(@I..@II)/$-2;f1
+ So, the total abundance is 8.5e-4 and the average mass is 15.3
  + We use these as an average metal collider in the graph
  + Assume metals are doubly ionized
  + Unsurprisingly, they make a negligible contribution

#+BEGIN_SRC python :results file :return pltfile
  import numpy as np
  import ds79
  from matplotlib import pyplot as plt
  import seaborn as sns

  pltfile = "test-Fdrag-components.pdf"

  w = np.logspace(-1.5, 3.5, 200)

  sns.set_color_codes()
  fig, ax = plt.subplots()

  colliders = ds79.DEFAULT_COLLIDERS + [ds79.Collider("CNO++", A=15.3, Z=2.0, abun=8.5e-4)]
  fdrag = ds79.Fdrag_components(w, T=8000, phi=10.0, n=100, colliders=colliders)

  colors = "rcmy"
  ftotal = np.zeros_like(w)
  for collider, color in zip(fdrag, colors):
      ax.plot(w, fdrag[collider][1], color=color, label=collider)
      ax.plot(w, fdrag[collider][0], color=color, ls='--', label="_nolabel_")
      ftotal += fdrag[collider][0] + fdrag[collider][1]
  ax.plot(w, ftotal, color="k", label="Total")
  ax.legend(title="Collider")
  ax.set(
      xscale="log",
      yscale="log",
      xlabel="Gas-grain velocity difference, $w$, km/s",
      ylabel=r"Drag force $/ (2 n k T) (\pi a^{2}) $",
  )
  sns.despine()
  fig.tight_layout()
  fig.savefig(pltfile)
#+END_SRC

#+RESULTS:
[[file:test-Fdrag-components.pdf]]
** Regimes in (v, \phi) space
#+BEGIN_SRC python :results file :return pltfile
  import numpy as np
  import ds79
  from matplotlib import pyplot as plt
  import seaborn as sns

  pltfile = "test-Fdrag-param-space.pdf"

  w, phi = np.meshgrid(
      np.logspace(-1.5, 3.5, 200),
      np.logspace(-2.0, 2.0, 200)
  )

  sns.set_color_codes()
  fig, ax = plt.subplots(figsize=(6, 6))

  colliders = ds79.DEFAULT_COLLIDERS + [ds79.Collider("CNO++", A=15.3, Z=2.0, abun=8.5e-4)]
  fdict = ds79.Fdrag_components(w, T=8000, phi=phi, n=100, colliders=colliders)

  # Total solid body drag
  fEpstein = np.sum([f[0] for f in fdict.values()], axis=0)
  # Total solid body plus Coulomb
  fTotal = np.sum([f[0] + f[1] for f in fdict.values()], axis=0)

  frac_Epstein = fEpstein / fTotal
  frac_proton = fdict["proton"][1] / fTotal
  frac_electron = fdict["electron"][1] / fTotal


  ax.contourf(w, phi, frac_Epstein, [0.5, 0.6, 0.7, 1.0], alpha=1.0,
             cmap="Blues")
  ax.contourf(w, phi, frac_proton, [0.5, 0.6, 0.7, 1.0], alpha=1.0,
             cmap="Reds")
  ax.contourf(w, phi, frac_electron, [0.5, 0.6, 0.7, 1.0], alpha=1.0,
             cmap="Greens")
  ax.contour(w, phi, fTotal,
             [0.1, 1.0, 10.0, 100.0, 1.e3, 1.e4, 1.e5],
             colors="w", linewidths=2.5)
  ax.contour(w, phi, fTotal,
             [0.1, 1.0, 10.0, 100.0, 1.e3, 1.e4, 1.e5],
             colors="k", linewidths=0.5)
  ax.axvline(10.0, color="w", lw=3, ls=":")
  ax.text(1.0, 0.04, "I", color="w", fontsize="xx-large")
  ax.text(150.0, 0.1, "II", color="w", fontsize="xx-large")
  ax.text(1.0, 10.0, "III", color="w", fontsize="xx-large")
  ax.text(16.0, 20.0, "IV", color="w", fontsize="xx-large")
  ax.text(150.0, 25.0, "V", color="w", fontsize="xx-large")
  ax.set(
      xscale="log",
      yscale="log",
      xlabel="Gas-grain velocity difference, $w$, km/s",
      ylabel=r"Grain potential, $|\phi|$",
  )
  sns.despine()
  fig.tight_layout()
  fig.savefig(pltfile)
#+END_SRC

#+RESULTS:
[[file:test-Fdrag-param-space.pdf]]


* On-axis 1d integration
+ As before, we normalize distances by the radiative turnaround radius
  + Velocities normalized by v_\infty
  + Times normalized by R_{**}/v_\infty
+ This means that the radiation force is just 1/2 in dimensionless units

#+BEGIN_SRC python :eval no :tangle test-stream-1d.py
  import sys
  import numpy as np
  from scipy.integrate import odeint
  from matplotlib import pyplot as plt
  import seaborn as sns
  import duststream as ds


  try: 
      STAR = sys.argv[1]
      VINF = float(sys.argv[2])
      LOGN = float(sys.argv[3])
      GRAIN = sys.argv[4]
      A = float(sys.argv[5])
  except:
      print(f"Usage: {sys.argv[0]} L4 VINF LOGN GRAIN A [ZOOM]")

  try: 
      ZOOM = float(sys.argv[6])
  except:
      ZOOM = 1.0


  L4 = {
      "MS10": 0.64,
      "MS20": 5.45,
      "MS40": 22.2,
      "BSG": 30.2,
  }
  eta = {
      "MS10": 0.0066,
      "MS20": 0.1199,
      "MS40": 0.4468,
      "BSG": 0.3079,
  }


  # Set minor parameters according to star and grain type
  Tgas = {
      "MS10": 8000.0,
      "MS20": 9000.0,
      "MS40": 1e4,
      "BSG": 8000.0,
  }

  if GRAIN == "gra":
      rho_d = 2.2
      if STAR in ["MS10", "BSG"]:
          phi_norm = 1.0
      else:
          phi_norm = 1.5
  else:
      rho_d = 3.5
      if STAR in ["MS10", "BSG"]:
          phi_norm = 0.7
      else:
          phi_norm = 1.4




  # Initial conditions
  Rstart = 2.5/ZOOM
  y0 = [Rstart, -1.0]

  stream = ds.DustStream(L4=L4[STAR], vinf=VINF, n=10**LOGN, a=A,
                         eta=eta[STAR], T=Tgas[STAR], phi_norm=phi_norm, rho_d=rho_d)

  streamid = f"{STAR}-v{int(VINF):03d}-n{int(10*LOGN):+02d}-{GRAIN}{int(100*A):03d}"

  figfile = sys.argv[0].replace('.py', f'-{streamid}.pdf')

  # Time grid
  t = np.linspace(0.0, 10.0/ZOOM, 5001)
  soln = odeint(ds.dydt_1d, y0, t, args=(stream,))
  t0 = t[soln[:, 1] >= 0.0].min()

  # Slippage velocity
  w = 1.0 + soln[:, 1]
  # Drift velocity
  # wdrift = 1.0 / alpha / soln[:, 0]

  sns.set_style('ticks')
  sns.set_color_codes('deep')
  fig, (ax, axp) = plt.subplots(2, 1, figsize=(4, 6))
  ax.plot(t - t0, soln[:, 0], label='$R/R_{0}$', zorder=3, lw=0.5)
  ax.plot(t - t0, soln[:, 1], label='$v / v_{\infty}$', lw=0.5)
  #ax.plot(t - t0, wdrift, ls='--', label='$w_\mathrm{drift} / v_{\infty}$')

  # ax.axhline(1.0/alpha, ls=':', color='k', lw=0.8)
  ax.axhspan(0.0, 1.0, color='k', alpha=0.1)
  ax.legend(loc="lower left")
  ax.set(
      xlabel=r'Time / $(R_{0} / v_{\infty})$',
      ylim=[-1.1, 2.1]
  )
  t2 = np.linspace(0.0, 20.0, 201)

  R1, R2 = 2e-4, 20.0

  x1, x2 = R1/stream.Rstarstar, R2/stream.Rstarstar
  w1, w2 = 0.03/stream.vinf, 2000.0/stream.vinf

  xpts = np.logspace(np.log10(x1), np.log10(x2), 151)
  wpts = np.logspace(np.log10(w1), np.log10(w2), 101)

  agrid = ds.total_accel(xpts[None, :], stream.vinf*wpts[:, None], stream)


  # Add dimensions back in for plotting
  xpts *= stream.Rstarstar
  x1 *= stream.Rstarstar
  x2 *= stream.Rstarstar

  wpts *= stream.vinf
  w1 *= stream.vinf
  w2 *= stream.vinf

  axp.contour(xpts, wpts, agrid, [0.0], linewidths=3, linestyles=":", colors="m")
  for z, cmap, dex in [[np.log10(agrid), "Blues", 10.0],
                       [np.log10(-agrid), "Reds", 4.0]]: 
      axp.contourf(xpts, wpts, z,
                   10, #[-0.5, 0.0, 0.5, 1.0, 1.5, 2.0],
                   vmax=np.nanmax(z), vmin=np.nanmax(z)-dex,
                   cmap=cmap)

  axp.plot(soln[:, 0]*stream.Rstarstar, w*stream.vinf, lw=4, color="w", alpha=0.5)
  axp.plot(soln[:, 0]*stream.Rstarstar, w*stream.vinf, lw=2, color="k", alpha=1.0)
  axp.axhline(stream.vinf, color='k', lw=0.5)
  axp.axvline(stream.Rstarstar, color='k', lw=0.5)
  axp.axvline(stream.R0, color='r', lw=2, ls="--")
  axp.set(xlabel='$R$, pc', ylabel='$w$, km/s',
          xlim=[x1, x2], ylim=[w1, w2],
          xscale="log", yscale="log",
          xticks=0.5*np.arange(7),
          yticks=[-1.0, -0.5, 0., 0.5, 1.0, 1.5])

  sns.despine()
  fig.tight_layout()
  fig.text(0.02, 0.97, '(a)')
  fig.text(0.02, 0.5, '(b)')
  fig.savefig(figfile)
  print(figfile, end='')

#+END_SRC

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 20 -2 gra 0.02
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v020-n-20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 10 -2 gra 0.02
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v010-n-20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 10 -2 gra 0.2
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v010-n-20-gra020.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 10 -2 sil 0.2
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v010-n-20-sil020.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 5 -2 gra 0.2
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v005-n-20-gra020.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 5 -2 sil 0.2
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v005-n-20-sil020.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 5 -2 sil 0.5
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v005-n-20-sil050.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 50 4 sil 0.5
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v050-n+40-sil050.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 100 4 sil 0.5
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v100-n+40-sil050.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 100 4 sil 0.2
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v100-n+40-sil020.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 100 4 sil 0.02
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v100-n+40-sil002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS20 20 -2 gra 0.02
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS20-v020-n-20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS40 20 -2 gra 0.02
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS40-v020-n-20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py BSG 20 -2 gra 0.02
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-BSG-v020-n-20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 20 -1.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v020-n-10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 20 0.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v020-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 40 0.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v040-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 60 0.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v060-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 80 0.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v080-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 100 0.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v100-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 150 0.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v150-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 60 1.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v060-n+10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 80 1.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v080-n+10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 100 1.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v100-n+10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 150 1.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v150-n+10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 200 1.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v200-n+10-gra002.pdf]]


#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 150 2.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v150-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 150 3.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v150-n+30-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 150 4.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v150-n+40-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 60 2.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v060-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 40 2.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v040-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 60 3.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v060-n+30-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 60 3.0 gra 0.2 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v060-n+30-gra020.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 60 3.0 sil 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v060-n+30-sil002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 60 3.0 sil 0.2 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v060-n+30-sil020.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 60 4.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v060-n+40-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 60 4.0 gra 0.5 
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v060-n+40-gra050.pdf]]


#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 150 3.0 gra 0.2 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v150-n+30-gra020.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS10 150 3.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS10-v150-n+30-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS20 150 1.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS20-v150-n+10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS40 150 1.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS40-v150-n+10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS40 150 1.0 gra 0.2 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS40-v150-n+10-gra020.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS40 150 1.0 gra 0.5 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS40-v150-n+10-gra050.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS40 50 1.0 gra 0.5 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS40-v050-n+10-gra050.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS40 20 1.0 gra 0.5 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS40-v020-n+10-gra050.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS40 300 1.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS40-v300-n+10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS40 300 0.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS40-v300-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS40 500 0.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS40-v500-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS20 300 0.0 gra 0.02 1.0
#+END_SRC

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS20 300 0.0 gra 0.01 
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS20-v300-n+0-gra001.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS20 500 0.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS20-v500-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS20 500 1.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS20-v500-n+10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python test-stream-1d.py MS20 500 2.0 gra 0.02 1.0
#+END_SRC

#+RESULTS:
[[file:test-stream-1d-MS20-v500-n+20-gra002.pdf]]

** Initial impressions
+ There are at least 4 parameters:
  + L4, v, n, a
  + [X] In principle \phi should be determined self-consistently
    + Now done
  + Everything else is minor: \rho_d, Q_p
+ For v_\infty in range 11 \to 80 km/s, we get the limit cycle behavior:
  + Dust is swept in past R_{** }and follows drift velocity
  + Gets turned around and shoots out
    + For v ~ 20 km/s we can go out at twice velocity that we came in, so that w = 60 km/s since that is right in the middle of the trough in the drag force
    + src_python{ds.DustStream(vinf=20, phi=15.0, a=0.04, L4=0.63, n=1.0e-1)}
  + Decelerated by electron drag while w is of order 2 v_\infty
  + Sudden deceleration and total re-coupling by proton drag when w falls to about 20 km/s 


** Functional dependence of the trajectory parameters
+ The net force map
  + The zero-contour at least does not depend on a or v
+ Grain size effects
  + Increasing size, a, reduces R_{\star\star} because \kappa_d = Q_P \sigma/m = 3 Q_p/(4 a \rho_d) is reduced and R_{\star\star} \prop \kappa_d L / v^2
  + But it does not effect equilibrium R because that is just the radius where w_drift = v
  + Does slightly effect minimum R because there is an overshoot below sonic drift radius R_sd (where w_drift = 10 km/s), which does depend on \sigma/m
+ Velocity effects
  + We can move from the damped v > 80 to oscillatory 11 < v < 80 to damped again v < 10  regimes, but this does not change the dust wave radius in physical units much
  + As velocity goes up, bowshock/wave radius R_0 gets smaller, so that dust wave separates
    + For instance ~MS10 (20,40,60,80) 0.0 gra 0.02~
    + At 20 km/s, R_0 is bigger than R_DW so there is no dust wave
    + At 40 km/s and greater, R_0 is smaller so the dust wave can form
    + As v increases, oscillations get floppier
      + Albeit, only in terms of R_{\star\star} - they are more or less the same in terms of R_SD
    + Finally, at 80 km/s we pass over to the damped oscillations
+ Density effects
  + As we increase the density, we reduce R_0 and R_SD
    + So minimum velocity for DW is little changed
    + [X] But how exactly does R_SD change with density?
      + It is at a fixed radiation parameter, \Xi = P_rad / P_gas
  + But R_{\star\star} is unchanged
    + so the oscillations get tighter since R_SD / R_{\star\star} is smaller
  + [X] /Speculation:/ at high enough density, we get into BW regime, where R_0 is also independent of density - in which case DW will merge in to BW (like when \alpha_drag > 100 in previous model)
    + This does seem to be true, but needs to be quantified more carefully
** Grain potential versus U_P (aka \Upsilon_P, aka \Xi)
+ This is roughly logarithmic
+ Graph in ~cloudy-dust-charging~ project
  + [[file:~/Dropbox/cloudy-dust-charging/phi-pratio.pdf]]
+ Reasonable approximation
  * \(\phi = 1.5 \log(U_{P}_{}/0.1) = 1.5 \bigl( \log(U_{P}_{}) + 2.3 \bigr)\)
    |   U_P |    \phi |
    |------+------|
    | 0.01 | -3.5 |
    |  0.1 | -0.0 |
    |    1 |  3.5 |
    |   10 |  6.9 |
    |  100 | 10.4 |
    | 1000 | 13.8 |
    |  1e4 | 17.3 |
    #+TBLFM: $2=1.5 log($1) + 3.45 ; %.1f
+ The above function is good for MS10 and BSG with carbon grains
  + Stellar type: hard spectrum (MS20, MS40) is about 1.5 times higher
  + Grain type: Si grains are about 1.5 times lower
+ Upsilon \Upsilon 𝚼 𝛶
+ Xi Ξ 𝛯 𝝣
+ R_\dag is the rip point, when P_rad/P_gas = \Xi_\dag
+ What would be a good replacement for \star\star?
  + R_\S or R_\subset or R_\supset or R_\wedge or R_\Leftrightarrow or R_\sim or R_\cap or \(R_\leadsto\) or \(R_{\Updownarrow}\) or \(R_{\hookrightarrow}\)
  + Not convinced by any of them
** Library for on-axis trajectories: ~onaxis_traject.py~
#+BEGIN_SRC sh
mkdir data
mkdir figs
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS20 500 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS20-v500-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 50 4.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v050-n+40-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 50 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v050-n+30-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 50 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v050-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 300 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v300-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 300 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v300-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 150 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v150-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 100 1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v100-n+10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 100 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v100-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 100 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v100-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 80 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v080-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 60 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v060-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 40 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v040-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 20 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v020-n+0-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 20 -1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v020-n-10-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 20 -3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v020-n-30-gra002.pdf]]

Very small grain
#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 80 4.0 gra 0.002
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v080-n+40-gra000.pdf]]

** Do plots of radii versus density

#+BEGIN_SRC sh :results file
python onaxis-stats-plot.py MS20 v300 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-stats-plot-MS20-v300-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-stats-plot.py MS20 v100 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-stats-plot-MS20-v100-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-stats-plot.py MS40 v500 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-stats-plot-MS40-v500-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-stats-plot.py MS10 v040 gra020
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-stats-plot-MS10-v040-gra020.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-stats-plot.py MS10 v040 sil002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-stats-plot-MS10-v040-sil002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-stats-plot.py MS10 v040 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-stats-plot-MS10-v040-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-stats-plot.py MS10 v080 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-stats-plot-MS10-v080-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-stats-plot.py MS10 v020 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-stats-plot-MS10-v020-gra002.pdf]]

** Normalize all radii by R_*
#+BEGIN_SRC sh :results file
python onaxis-norm-plot.py MS10 v080 sil002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-norm-plot-MS10-v080-sil002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-norm-plot.py MS10 v080 gra020
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-norm-plot-MS10-v080-gra020.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-norm-plot.py MS10 v080 sil000
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-norm-plot-MS10-v080-sil000.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-norm-plot.py MS10 v080 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-norm-plot-MS10-v080-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-norm-plot.py MS10 v040 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-norm-plot-MS10-v040-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-norm-plot.py MS10 v100 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-norm-plot-MS10-v100-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-norm-plot.py MS10 v300 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-norm-plot-MS10-v300-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-norm-plot.py MS20 v300 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-norm-plot-MS20-v300-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-norm-plot.py MS40 v500 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-norm-plot-MS40-v500-gra002.pdf]]

#+BEGIN_SRC sh :results file
python onaxis-norm-plot.py MS40 v300 gra002
#+END_SRC

#+RESULTS:
[[file:figs/onaxis-norm-plot-MS40-v300-gra002.pdf]]




* TODO Make some videos of the phase space trajectories

* DONE 3d trajectories
CLOSED: [2018-05-09 Wed 18:13]
+ Actually 2D in non-magnetic case, since each trajectory is a plane curve


V = 80 and n = 10

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 80 1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v080-n+10-gra002-Y0001.pdf]]

V = 60 and n = 10, at a load of different Y0

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 60 1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+10-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 60 1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+10-gra002-Y0100.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.3 MS10 60 1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+10-gra002-Y0300.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.4 MS10 60 1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+10-gra002-Y0400.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.5 MS10 60 1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+10-gra002-Y0500.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.6 MS10 60 1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+10-gra002-Y0600.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 1.0 MS10 60 1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+10-gra002-Y1000.pdf]]

V = 60 and n = 1

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 60 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+00-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.01 MS10 60 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+00-gra002-Y0010.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 60 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+00-gra002-Y0100.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.3 MS10 60 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+00-gra002-Y0300.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.4 MS10 60 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+00-gra002-Y0400.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.5 MS10 60 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+00-gra002-Y0500.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.6 MS10 60 0.0 gra 0.02
#+END_SRC

V = 40 and n = 1  

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 40 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+00-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 40 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+00-gra002-Y0100.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 40 0.0 sil 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+00-sil002-Y0100.pdf]]

V = 100 and n = 1

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 100 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+00-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 100 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+00-gra002-Y0100.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.3 MS10 100 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+00-gra002-Y0300.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.45 MS10 100 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+00-gra002-Y0450.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.5 MS10 100 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+00-gra002-Y0500.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.52 MS10 100 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+00-gra002-Y0520.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.6 MS10 100 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+00-gra002-Y0600.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.7 MS10 100 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+00-gra002-Y0700.pdf]]

Higher density

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 100 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+20-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 100 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+20-gra002-Y0100.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.3 MS10 100 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+20-gra002-Y0300.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.4 MS10 100 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+20-gra002-Y0400.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.5 MS10 100 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+20-gra002-Y0500.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.6 MS10 100 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+20-gra002-Y0600.pdf]]


Even higher density

#+BEGIN_SRC sh :results file
python onaxis_traject.py MS10 100 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/on-axis-MS10-v100-n+30-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.0 MS10 100 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+30-gra002-Y0000.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 100 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+30-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 100 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+30-gra002-Y0100.pdf]]


Lower velocity, higher density

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 60 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n+30-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 40 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+30-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 40 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+20-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 40 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+20-gra002-Y0100.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.3 MS10 40 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+20-gra002-Y0300.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.5 MS10 40 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+20-gra002-Y0500.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 40 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+00-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 40 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+00-gra002-Y0100.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.3 MS10 40 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+00-gra002-Y0300.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.5 MS10 40 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v040-n+00-gra002-Y0500.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 50 1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v050-n+10-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 50 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v050-n+00-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 50 -1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v050-n-10-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 55 -1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v055-n-10-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 60 -1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v060-n-10-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 65 -1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v065-n-10-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 70 -1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v070-n-10-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 70 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v070-n+00-gra002-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 70 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v070-n+00-gra002-Y0100.pdf]]

Bigger grain

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 70 0.0 gra 0.2
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v070-n+00-gra020-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 100 0.0 gra 0.2
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v100-n+00-gra020-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 200 2.0 gra 0.2
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v200-n+20-gra020-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.001 MS10 200 4.0 gra 0.2
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v200-n+40-gra020-Y0001.pdf]]

#+BEGIN_SRC sh :results file
python twod_traject.py 0.1 MS10 150 4.0 sil 0.2
#+END_SRC

#+RESULTS:
[[file:figs/twod-MS10-v150-n+40-sil020-Y0100.pdf]]



** Maps of the 2d trajectories


#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 70 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v070-n+00-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 70 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v070-n+30-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 60 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v060-n+30-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 150 3.0 gra 0.02
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 300 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v300-n+30-gra002.pdf]]


#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 150 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v150-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 100 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v100-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 80 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v080-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 60 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v060-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 40 2.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v040-n+20-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 40 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v040-n+00-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 100 3.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v100-n+30-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 100 0.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v100-n+00-gra002.pdf]]

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 100 -1.0 gra 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v100-n-10-gra002.pdf]]

Looking at the sequence of 1e3 pcc models, the inner radius stays the same, but the outer radius reduces as velocity increases. 

Smaller dust grains - sticks more closely to R_\dag and R_drift

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 60 2.0 gra 0.002
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v060-n+20-gra000.pdf]]

Larger dust grains - penetrate in deeper and bounce out further 

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 60 2.0 gra 0.2
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v060-n+20-gra020.pdf]]

Silicate grains instead of graphite - has about 1.7 times the radius.  Otherwise, similar.  Also, take an unconscionably long time to run. 

#+BEGIN_SRC sh :results file
python twod-stream-map.py MS10 60 2.0 sil 0.02
#+END_SRC

#+RESULTS:
[[file:twod-stream-map-MS10-v060-n+20-sil002.pdf]]


* TODO Adding the Lorentz force
+ First do the guiding center approximation for Larmor radius \to 0
+ Implemented in [[file:frozen_trajectory.py]]
+ Testing if it is working

#+BEGIN_SRC sh :results file
python frozen_trajectory.py MS10 60 2.0 gra 0.02 0.0 0.53 0.0
#+END_SRC

#+RESULTS:
[[file:figs/frozen-Y0530-Z0000-MS10-v060-n+20-gra002-th000.pdf]]

Now do maps like before 
